"use client"
import "./globals.css"
import { Inter } from "next/font/google"
import Footer from "@/components/Footer"
import Script from "next/script"
import Navbar from "@/components/Navbar"

import { usePathname } from "next/navigation"
import { BrowserRouter } from "react-router-dom"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
<BrowserRouter>
{children}
</BrowserRouter>
        

        <Footer />

        <Script strategy="beforeInteractive" src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></Script>
      </body>
    </html>
  )
}
